podinfo:
  replicaCount: 9
  ui:
    message: "ArgoCD Workshop Sample 2a"
    color: "#008800"
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: "argocd-workshop-s2a"
        paths:
          - path: "/"
            pathType: "Prefix"
