apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s4b-application
  namespace: infra-argocd
spec:
  # The project the application belongs to.
  project: default
  source:
    # Can point to either a Helm chart repo or a git repo.
    repoURL: https://github.com/stan1ey-shen/argocd-workshop.git
    # For Helm, this refers to the chart version.
    targetRevision: HEAD
    # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
    path: s4-application/http-echo
    kustomize:
      namePrefix: s4b-application-
      patches:
        - target:
            kind: Deployment
            name: http-echo
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/args/0
              value: -text="Hello Gorilla, this is Argo CD Workshop s4b."
        - target:
            kind: Ingress
            name: http-echo
          patch: |-
            - op: replace
              path: /spec/rules/0/host
              value: argocd-workshop-s4b.192.168.4.154.sslip.io
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gorilla
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      enabled: true # Enables automated syncing of the application ( true by default ).
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true
